### ISSUE TITLE
Extensions should be ?? licensed

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/fox#2]
Should the template assign the MPL license (and header) to extensions? Whatever license we pick we also need to include a LICENSE file in the template.

**Comment by defunctzombie** [comment]
It seems that in the package.json we list MIT - but in the src we've put the MPL header.

**Comment by jhurliman** [comment]
I don't see where we are putting an MPL header into extension source code. The fox tool itself is MPL licensed, extensions default to MIT licensed.
