### ISSUE TITLE
Is yarn necessary?

### ISSUE THREAD

**Issue by amacneil** [foxglove/fox#20]
We should aim to keep the cognitive overhead as low as possible for creating and managing extensions. Many people who create extensions will not be intimately familiar with the JS ecosystem, or care to learn several tools just to get started.

The extension template is created with yarn by default, which might be nice for power users, but requires an understanding of what npm is before you can even use it. Googling yarn issues results in a confusing collection of yarn 1 docs, yarn 2 docs, and occasionally places where you need to just read the npm docs and then guess at what yarn is doing. 

I would advocate for bootstrapping npm out of the box to make things simpler for the user, unless there is a strict reason we need yarn. People who want to use yarn will know enough to infer the commands they should use.

**Comment by jhurliman** [comment]
Relevant: https://www.npmjs.com/package/yarpm

**Comment by defunctzombie** [comment]
I think we should stick to yarn for now since we use it for all our own stuff. I agree the yarn v1 v2 v3 is a nightmare but not something to tackle for now. npm has its own annoyances but maybe now that it is under a company that can fund and develop it we will see it be a viable option.
