### ISSUE TITLE
Ability to open sibling panels

### ISSUE THREAD

**Issue by jessicaaustin** [foxglove/fox#28]
I'm building an extension that shows data from a topic, and I would like to add the ability to open a sibling plot to show values over time, similar to the functionality in the Diagnostics panel and Raw Messages panel. 

It looks like those panels call `openSiblingPlotPanel` and `openSiblingStateTransitionsPanel`, but when I try to import those from studio-base I run into all kinds of issues with dependencies. I'm guessing the "right way" to do this would be to have an extension API method that would allow opening sibling panels?

If there are other ways to achieve this please let me know! I think this is a particularly valuable feature in the base Studio app and would love to bring it into my extension.

**Comment by defunctzombie** [comment]
@jessicaaustin would you mind re-filing this in the https://github.com/foxglove/studio repo? We can track it better there. And yea - I'm thinking the context would have a method whereby you can open a sibling panel by its fully qualified ID.

**Comment by jessicaaustin** [comment]
https://github.com/foxglove/studio/issues/1914

**Comment by defunctzombie** [comment]
Thank you! Closing this out in favor of the studio issue.
