### ISSUE TITLE
Engines `@foxglove/studio` is confusing when we also have a `@foxglove/studio` package

### ISSUE THREAD

**Issue by defunctzombie** [foxglove/fox#3]
For engines we should use `foxglovestudio` or some non-package looking name. Right now it looks like you have a dependency on @foxglove/studio and it is also an engine.

**Comment by jhurliman** [comment]
`npm` (and possibly other tooling) warn about unknown engines. I'm going to drop this for now, when we need it in the future I think a separate `"foxglovestudio": {}` entry in package.json will give us more flexibility and avoid colliding with existing tooling.
