### ISSUE TITLE
Runtime error when loading custom extension

### ISSUE THREAD

**Issue by stefan-pdx** [foxglove/fox#30]
**Description**
After installing a custom extension, Foxglove Studio generates a `ReferenceError: exports is not defined` (`ExtensionRegistryProvider.tsx:71`).

- Version: @foxglove/studio@0.18.2, @foxglove/fox@0.2.1
- Platform: macOS 11.6

**Steps To Reproduce**
```
$ npx @foxglove/fox create myExtensionName
$ cd myExtensionName
$ npm run build
$ npm run local-install
```

Open Foxglove Studio and toggle Developer Tools to see the error.

**Expected Behavior**
Extension should load successfully and the custom panel should be visible in the "Add panel" view.

**Actual Behavior**
An error is generated in the console output and the custom panel is not visible in the "Add panel" view.

**Comment by jtbandes** [comment]
To aid in debugging can you paste the bundled JS code that was generated for your custom extension? (Feel free to remove any sensitive information — just interested in the overall structure of the JS bundle)

**Comment by jtbandes** [comment]
Interesting – I can't reproduce the problem on my machine. Can you also zip up the extension from `~/.foxglove-studio/extensions/` and include that?

**Comment by defunctzombie** [comment]
@stefan-pdx can you try the following steps (after uninstalling any custom extensions previously installed to rule those out):

```
$ npx @foxglove/fox@latest create myExtensionName
$ cd myExtensionName
$ npm run build
$ npm run local-install
```

> Note: the change to the npx command line to ensure you run the latest @foxglove/fox version

**Comment by stefan-pdx** [comment]
Ah. After removing `~/.foxglove-studio/` and reinstalling Foxglove, I'm not able to recreate the issue.

Looking back at the old folder, I had what appears to be the `@foxglove/fox` package installed as an extension which I believe could have been the culprit. As to how that package got installed there in the first place... must've been user error.

I'm able to successfully load extensions at this point! Sorry for the false alarm. ❤️
