### ISSUE TITLE
source-list-map not found 404

### ISSUE THREAD

**Issue by TobiMiller** [foxglove/fox#34]
Hey, 
i want to start to create an own Audio Extension. Not sure if i will get it working :D i already despair at the first step. 
The command: 
`npx @foxglove/fox create`

generates an error:

```
Need to install the following packages:
  @foxglove/fox
Ok to proceed? (y) 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/source-list-map/-/source-list-map-2.0.1.tgz
npm ERR! 404 
npm ERR! 404  'source-list-map@https://packagecloud.io/github/git-lfs/npm/source-list-map/-/source-list-map-2.0.1.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

can it be fixed on my side?

**Comment by jtbandes** [comment]
Hi – I'm not able to reproduce this issue, can you try `npx @foxglove/fox@latest` instead of `npx @foxglove/fox`?

**Comment by TobiMiller** [comment]
it is working on my ubuntu 20.04 now :) idk what the problem is on 18.04. `npx @foxglove/fox@latest` didnt work
