### ISSUE TITLE
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.

### ISSUE THREAD

**Issue by TobiMiller** [foxglove/fox#35]
Hey,

I've got the audio stream for my planned audio extension working. But i think it is not well implemented. For that reason i want to use third party PCM audio plugins.
But when i include them and want to  build the project. i get this error:
```
Error: build failed: Errors:
ModuleNotFoundError: Module not found: Error: Can't resolve 'fs' in '/home/tobias/src/studio-extension-audio/node_modules/bindings'
ModuleNotFoundError: Module not found: Error: Can't resolve 'path' in '/home/tobias/src/studio-extension-audio/node_modules/bindings'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
ModuleNotFoundError: Module not found: Error: Can't resolve 'path' in '/home/tobias/src/studio-extension-audio/node_modules/file-uri-to-path'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
    at /home/tobias/src/studio-extension-audio/node_modules/@foxglove/fox/dist/build.js:46:35
    at /home/tobias/src/studio-extension-audio/node_modules/webpack/lib/HookWebpackError.js:68:3
    at Hook.eval [as callAsync] (eval at create (/home/tobias/src/studio-extension-audio/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/tobias/src/studio-extension-audio/node_modules/tapable/lib/Hook.js:18:14)
    at Cache.shutdown (/home/tobias/src/studio-extension-audio/node_modules/webpack/lib/Cache.js:150:23)
    at /home/tobias/src/studio-extension-audio/node_modules/webpack/lib/Compiler.js:1127:15
    at Hook.eval [as callAsync] (eval at create (/home/tobias/src/studio-extension-audio/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/tobias/src/studio-extension-audio/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.close (/home/tobias/src/studio-extension-audio/node_modules/webpack/lib/Compiler.js:1121:23)
    at /home/tobias/src/studio-extension-audio/node_modules/@foxglove/fox/dist/build.js:38:22
error Command failed with exit code 1.```

You know the problem and how to fix that? :)

**Comment by defunctzombie** [comment]
@TobiMiller Is the 3rd party PCM audio plugin package something that is designed for running in the browser or is this package targeting node.js only?

**Comment by TobiMiller** [comment]
@defunctzombie 

i cant tell you. i tried "speaker" and "audify". both use "require" instead of "import ... from" in their example code. 

https://www.npmjs.com/package/speaker
https://www.npmjs.com/package/audify

**Comment by defunctzombie** [comment]
@TobiMiller both of those look like "server only" packages to me. What I mean by that is they will require either c++ compiled code or a system library present. Neither of which works with how we package Studio or what studio extensions can do. The `audify` package might have something promising cause they do mention Electron but still looks like they require native compiled modules.

What you'll want to look for is some library that is "javascript (typescript) only", "javascript native", or "browser compatible". Something that either uses browser APIs or is written entirely in javascript and doesn't depend on any 3rd party libraries on your computer.

**Comment by TobiMiller** [comment]
ok thank you :) any chance to debug plugins with console.log()?

**Comment by defunctzombie** [comment]
@TobiMiller does using console.log in your extension not work? I believe those should show up in developer tools.

**Comment by TobiMiller** [comment]
@defunctzombie I assumed that extensions only work with the desktop app. How do I get the browser developer tools to appear in the desktop app?

**Comment by defunctzombie** [comment]
From the app menu:

> View -> Advanced -> Toggle Developer Tools

I'm gonna close this issue as the modules in question are not ones that are supported for use with extensions. If you run into any other issues feel free to open new tickets or hop on our slack! Happy to help out as you build your extension.

**Comment by TobiMiller** [comment]
> From the app menu:
> 
> > View -> Advanced -> Toggle Developer Tools
> 
> I'm gonna close this issue as the modules in question are not ones that are supported for use with extensions. If you run into any other issues feel free to open new tickets or hop on our slack! Happy to help out as you build your extension.

i compile foxglove desktop app by myself with "yarn serve" & "yarn start" now.  the app starts with dev tools with this commands ;) `view -> advanced --> toggle developer tools` is not available under linux or i dont find it.

**Comment by jtbandes** [comment]
You might need to press the Alt key to show the menus on linux or windows.

**Comment by defunctzombie** [comment]
I believe the keyboard shortcut (same as what you would use in chrome) should also work (it did for me on my mac).
